name: First Workflow

# on: [push]
# on: workflow_dispatch
on: push

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Wy≈õwietl komunikat
              run: echo "Komunikat"
            - name: Command in Multiline
              run: |
                node -v
                npm -v
              
