name: Third Workflow

on: push

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Wylistuj zawartosc katalogu roboczego i skopiuj repozytorium 
              run: |
                pwd
                ls -al
            #- uses: actions/checkout@v4
            - name: Koppiuj pliki
              run: |
                git init
                git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
                git fetch origin
                git checkout main   
            - name: Wylistuj zawartosc katalogu roboczego  po skopiowaniu repozytorium 
              run: ls -a