name: Third Workflow

on: push

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Wyświetl Wersję Node
              run: |
                pwd
                ls -al