name: Third Workflow

on: push

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Wylistuj zawartosc katalogu roboczego i skopiuj repozytorium 
              run: |
                pwd
                ls -al
            - uses: actions/checkout@v4
            - name: Wylistuj zawartosc katalogu roboczego  po skopiowaniu repozytorium 
              run: ls -al