name: Third Workflow

on: push

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
            - name: Wylistuj zawartosc katalogu roboczego i skopiuj repozytorium 
              run: |
                pwd
                ls -al
            #- uses: actions/checkout@v4
            - name: Koppiuj pliki
              run: |
                git init
                git remote add master https://@GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
                git fech origin
                git checkout master
            - name: Wylistuj zawartosc katalogu roboczego  po skopiowaniu repozytorium 
              run: ls -a